---
engines:
 rubocop:
   enabled: true

pylint:
  enabled: true
  python_version: 3

exclude_paths:
  - '.github/**'
  - '**.md'
  - 'docs/**'
  - ReplicatedFocusingBeliefPropagation/__init__.py
  - ReplicatedFocusingBeliefPropagation/rfbp/__init__.py
  - './ReplicatedFocusingBeliefPropagation/rfbp/test/**'
  - './ReplicatedFocusingBeliefPropagation/rfbp/magnetization.py'
