name: rFBP Docs CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2

    - name: 'Update apt'
      run: sudo apt update

    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install sphinx dependencies
      run: |
        python -m pip install sphinx
        python -m pip install sphinxcontrib-napoleon
        python -m pip install sphinxcontrib-programoutput

    - name: Install breathe
      run: |
        python -m pip install breathe

    - name: Install Doxygen
      run: |
        sudo apt install doxygen

    - name: Build C++ API
      run: |
        doxygen

    - name: Build Python API
      run: |
        cd docs
        cd sphinxtext
        make clean
        make html
        cd ..
        cd ..
